### ISSUE TITLE
Download of matrix fails on version 0.0.2

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/hca-matrix-downloader#3]
I tried a run yesterday with the following command:

```
hca-matrix-downloader -p 'Single cell transcriptome analysis of human pancreas' -f mtx -o out -f 'loom'
```
(well, Galaxy did)

it generated the following error:

```
Contacting the Matrix API using the query: {"filter": {"op": "=", "value": "Single cell transcriptome analysis of human pancreas", "field": "project.project_core.project_short_name"}, "format": "loom"}
c7b2abf1-8048-4378-b0f9-898d83aa3f05
Traceback (most recent call last):
  File "/usr/local/tools/_conda/envs/__hca-matrix-downloader@0.0.2/bin/hca-matrix-downloader", line 12, in <module>
    sys.exit(main())
  File "/usr/local/tools/_conda/envs/__hca-matrix-downloader@0.0.2/lib/python3.7/site-packages/hca_matrix_service/client.py", line 75, in main
    zipfile.ZipFile(matrix_zip_filename).extractall()
  File "/usr/local/tools/_conda/envs/__hca-matrix-downloader@0.0.2/lib/python3.7/zipfile.py", line 1222, in __init__
    self._RealGetContents()
  File "/usr/local/tools/_conda/envs/__hca-matrix-downloader@0.0.2/lib/python3.7/zipfile.py", line 1289, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

any ideas?

**Comment by pcm32** [comment]
I reckon that there must be a problem in the wrapper as I assume that `-f` should only be passed once, right?

**Comment by pcm32** [comment]
ok, this doesn't happen with the latest version on development, will do a release and trigger the conda process.
